/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void setMap(GButton source, GEvent event) { //_CODE_:genMap:451647:
  applySetting(tempVar);
  generateSeed();
  setnewMap();
  syncGUI();
} //_CODE_:genMap:451647:

public void oEcon(GButton source, GEvent event) { //_CODE_:openEcon:987711:
  economicsSet.setVisible(true);
} //_CODE_:openEcon:987711:

public void oEnv(GButton source, GEvent event) { //_CODE_:openEnv:591581:
  environmentSet.setVisible(true);
} //_CODE_:openEnv:591581:

public void setJ(GButton source, GEvent event) { //_CODE_:presetJ:376584:
  tempVar[0] = 0.1;
  tempVar[1] = 1;
  tempVar[2] = 0.5;
  tempVar[3] = 1;
  tempVar[4] = 0.3;
  
  syncGUI();
  applySetting(tempVar);
  noiseSeed(653087);
  setnewMap();
} //_CODE_:presetJ:376584:

public void setM(GButton source, GEvent event) { //_CODE_:presetM:203186:
  tempVar[0] = 0.1;
  tempVar[1] = 0;
  tempVar[2] = 0.5;
  tempVar[3] = 1;
  tempVar[4] = 1;
  
  syncGUI();
  applySetting(tempVar);
  noiseSeed(222464);
  setnewMap();
} //_CODE_:presetM:203186:

public void setO(GButton source, GEvent event) { //_CODE_:presetO:755041:
  tempVar[0] = 0.1;
  tempVar[1] = 1;
  tempVar[2] = 1;
  tempVar[3] = 0;
  tempVar[4] = 0.12;
  
  
  applySetting(tempVar);
  syncGUI();
  noiseSeed(169654);
  setnewMap();
} //_CODE_:presetO:755041:

public void resetSetting(GButton source, GEvent event) { //_CODE_:resetMap:404340:
  startTempVars();
  syncGUI();
  resetMap();
} //_CODE_:resetMap:404340:

synchronized public void draw_envrio(PApplet appc, GWinData data) { //_CODE_:environmentSet:589896:
  appc.background(175, 225, 175);
} //_CODE_:environmentSet:589896:

public void toggleOcean(GCheckbox source, GEvent event) { //_CODE_:oceanCheck:417087:
  boolean setState = oceanCheck.isSelected();
  if (setState == false) {
    tempVar[1] = 0;
  }
  else {
    tempVar[1] = 1;
  }
} //_CODE_:oceanCheck:417087:

public void toggleMountain(GCheckbox source, GEvent event) { //_CODE_:mountainCheck:680878:
  boolean setState = mountainCheck.isSelected();
  if (setState == false) {
    tempVar[3] = 0;
  }
  else {
    tempVar[3] = 1;
  }
} //_CODE_:mountainCheck:680878:

public void sliderOcean(GCustomSlider source, GEvent event) { //_CODE_:setOcean:783830:
  tempVar[2] = setOcean.getValueF();
} //_CODE_:setOcean:783830:

public void sliderMountain(GCustomSlider source, GEvent event) { //_CODE_:setMountain:234560:
  tempVar[4] = setMountain.getValueF();
} //_CODE_:setMountain:234560:

public void sliderRain(GCustomSlider source, GEvent event) { //_CODE_:setRain:860061:
  tempVar[0] = setRain.getValueF();
} //_CODE_:setRain:860061:

public void cEn(GButton source, GEvent event) { //_CODE_:closeEnviro:633859:
  environmentSet.setVisible(false);
} //_CODE_:closeEnviro:633859:

synchronized public void draw_econ(PApplet appc, GWinData data) { //_CODE_:economicsSet:983638:
  appc.background(152, 216, 219);
} //_CODE_:economicsSet:983638:

public void sliderGDP(GCustomSlider source, GEvent event) { //_CODE_:setGDP:722549:
  gdpPerCapita = setGDP.getValueI();
} //_CODE_:setGDP:722549:

public void sliderMuni(GCustomSlider source, GEvent event) { //_CODE_:setMuni:650462:
  municipalBudget = setMuni.getValueI();
} //_CODE_:setMuni:650462:

public void sliderComm(GCustomSlider source, GEvent event) { //_CODE_:setComm:829493:
  commuteTolerances = setComm.getValueI();
} //_CODE_:setComm:829493:

public void sliderPopG(GCustomSlider source, GEvent event) { //_CODE_:setPopG:362966:
  populationGrowthRate = setPopG.getValueF();
} //_CODE_:setPopG:362966:

public void sliderPopDen(GCustomSlider source, GEvent event) { //_CODE_:setPopDen:748355:
  populationDensity = setPopDen.getValueI();
} //_CODE_:setPopDen:748355:

public void sliderEconR(GCustomSlider source, GEvent event) { //_CODE_:setEconR:757411:
  economicRecessionRate = setEconR.getValueF();
} //_CODE_:setEconR:757411:

public void cEcon(GButton source, GEvent event) { //_CODE_:closeEconomics:835496:
  economicsSet.setVisible(false);
} //_CODE_:closeEconomics:835496:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  genMap = new GButton(this, 560, 19, 80, 30);
  genMap.setText("Generate Map");
  genMap.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  genMap.addEventHandler(this, "setMap");
  openEcon = new GButton(this, 15, 420, 80, 35);
  openEcon.setText("Economics Setting");
  openEcon.setLocalColorScheme(GCScheme.RED_SCHEME);
  openEcon.addEventHandler(this, "oEcon");
  openEnv = new GButton(this, 15, 350, 80, 35);
  openEnv.setText("Envrionment Setting");
  openEnv.setLocalColorScheme(GCScheme.RED_SCHEME);
  openEnv.addEventHandler(this, "oEnv");
  presetJ = new GButton(this, 1105, 385, 80, 30);
  presetJ.setText("Island");
  presetJ.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  presetJ.addEventHandler(this, "setJ");
  presetM = new GButton(this, 1105, 315, 80, 30);
  presetM.setText("Mountain Rage");
  presetM.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  presetM.addEventHandler(this, "setM");
  presetO = new GButton(this, 1104, 455, 80, 30);
  presetO.setText("Ocean Rage");
  presetO.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  presetO.addEventHandler(this, "setO");
  resetMap = new GButton(this, 560, 66, 80, 30);
  resetMap.setText("Reset");
  resetMap.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  resetMap.addEventHandler(this, "resetSetting");
  environmentSet = GWindow.getWindow(this, "Envrionment", 0, 0, 400, 300, JAVA2D);
  environmentSet.noLoop();
  environmentSet.setActionOnClose(G4P.KEEP_OPEN);
  environmentSet.addDrawHandler(this, "draw_envrio");
  oceanCheck = new GCheckbox(environmentSet, 35, 29, 130, 20);
  oceanCheck.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  oceanCheck.setText("Allow Ocean");
  oceanCheck.setOpaque(false);
  oceanCheck.addEventHandler(this, "toggleOcean");
  oceanCheck.setSelected(true);
  mountainCheck = new GCheckbox(environmentSet, 235, 27, 130, 20);
  mountainCheck.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  mountainCheck.setText("Allow Mountain");
  mountainCheck.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  mountainCheck.setOpaque(false);
  mountainCheck.addEventHandler(this, "toggleMountain");
  mountainCheck.setSelected(true);
  setOcean = new GCustomSlider(environmentSet, 35, 81, 130, 55, "grey_blue");
  setOcean.setShowValue(true);
  setOcean.setShowLimits(true);
  setOcean.setLimits(0.5, 0.0, 1.0);
  setOcean.setNbrTicks(5);
  setOcean.setShowTicks(true);
  setOcean.setNumberFormat(G4P.DECIMAL, 2);
  setOcean.setOpaque(false);
  setOcean.addEventHandler(this, "sliderOcean");
  setMountain = new GCustomSlider(environmentSet, 235, 82, 130, 54, "grey_blue");
  setMountain.setShowValue(true);
  setMountain.setShowLimits(true);
  setMountain.setLimits(0.3, 0.0, 1.0);
  setMountain.setNbrTicks(5);
  setMountain.setShowTicks(true);
  setMountain.setNumberFormat(G4P.DECIMAL, 2);
  setMountain.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  setMountain.setOpaque(false);
  setMountain.addEventHandler(this, "sliderMountain");
  setRain = new GCustomSlider(environmentSet, 135, 205, 130, 55, "grey_blue");
  setRain.setShowValue(true);
  setRain.setShowLimits(true);
  setRain.setLimits(0.1, 0.0, 1.0);
  setRain.setNbrTicks(5);
  setRain.setShowTicks(true);
  setRain.setNumberFormat(G4P.DECIMAL, 2);
  setRain.setOpaque(false);
  setRain.addEventHandler(this, "sliderRain");
  enviro1 = new GLabel(environmentSet, 35, 54, 130, 20);
  enviro1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  enviro1.setText("Ocean Intensity");
  enviro1.setOpaque(false);
  enviro2 = new GLabel(environmentSet, 235, 54, 131, 20);
  enviro2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  enviro2.setText("Mountain Intensity");
  enviro2.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  enviro2.setOpaque(false);
  enviro3 = new GLabel(environmentSet, 135, 177, 130, 20);
  enviro3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  enviro3.setText("Rain Intensity");
  enviro3.setOpaque(false);
  closeEnviro = new GButton(environmentSet, 312, 261, 80, 30);
  closeEnviro.setText("Close");
  closeEnviro.setLocalColorScheme(GCScheme.RED_SCHEME);
  closeEnviro.addEventHandler(this, "cEn");
  economicsSet = GWindow.getWindow(this, "Economics", 0, 0, 400, 400, JAVA2D);
  economicsSet.noLoop();
  economicsSet.setActionOnClose(G4P.KEEP_OPEN);
  economicsSet.addDrawHandler(this, "draw_econ");
  setGDP = new GCustomSlider(economicsSet, 47, 72, 130, 55, "grey_blue");
  setGDP.setShowValue(true);
  setGDP.setShowLimits(true);
  setGDP.setLimits(50000, 0, 100000);
  setGDP.setNbrTicks(5);
  setGDP.setShowTicks(true);
  setGDP.setNumberFormat(G4P.INTEGER, 0);
  setGDP.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  setGDP.setOpaque(false);
  setGDP.addEventHandler(this, "sliderGDP");
  setMuni = new GCustomSlider(economicsSet, 223, 72, 130, 55, "grey_blue");
  setMuni.setShowValue(true);
  setMuni.setShowLimits(true);
  setMuni.setLimits(50000, 1000, 1000000);
  setMuni.setNbrTicks(5);
  setMuni.setShowTicks(true);
  setMuni.setNumberFormat(G4P.INTEGER, 0);
  setMuni.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  setMuni.setOpaque(false);
  setMuni.addEventHandler(this, "sliderMuni");
  setComm = new GCustomSlider(economicsSet, 47, 272, 130, 55, "grey_blue");
  setComm.setShowValue(true);
  setComm.setShowLimits(true);
  setComm.setLimits(150, 50, 400);
  setComm.setNbrTicks(5);
  setComm.setShowTicks(true);
  setComm.setNumberFormat(G4P.INTEGER, 0);
  setComm.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  setComm.setOpaque(false);
  setComm.addEventHandler(this, "sliderComm");
  setPopG = new GCustomSlider(economicsSet, 223, 172, 130, 55, "grey_blue");
  setPopG.setShowValue(true);
  setPopG.setShowLimits(true);
  setPopG.setLimits(0.05, 0.0, 0.2);
  setPopG.setNbrTicks(5);
  setPopG.setShowTicks(true);
  setPopG.setNumberFormat(G4P.DECIMAL, 2);
  setPopG.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  setPopG.setOpaque(false);
  setPopG.addEventHandler(this, "sliderPopG");
  setPopDen = new GCustomSlider(economicsSet, 223, 272, 130, 55, "grey_blue");
  setPopDen.setShowValue(true);
  setPopDen.setShowLimits(true);
  setPopDen.setLimits(10, 1, 50);
  setPopDen.setNbrTicks(5);
  setPopDen.setShowTicks(true);
  setPopDen.setNumberFormat(G4P.INTEGER, 0);
  setPopDen.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  setPopDen.setOpaque(false);
  setPopDen.addEventHandler(this, "sliderPopDen");
  setEconR = new GCustomSlider(economicsSet, 47, 173, 130, 55, "grey_blue");
  setEconR.setShowValue(true);
  setEconR.setShowLimits(true);
  setEconR.setLimits(0.1, 0.0, 1.0);
  setEconR.setNbrTicks(5);
  setEconR.setShowTicks(true);
  setEconR.setNumberFormat(G4P.DECIMAL, 2);
  setEconR.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  setEconR.setOpaque(false);
  setEconR.addEventHandler(this, "sliderEconR");
  closeEconomics = new GButton(economicsSet, 310, 360, 80, 30);
  closeEconomics.setText("Close");
  closeEconomics.setLocalColorScheme(GCScheme.RED_SCHEME);
  closeEconomics.addEventHandler(this, "cEcon");
  label1 = new GLabel(economicsSet, 47, 43, 130, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("GDP Per Capita");
  label1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label1.setOpaque(false);
  label2 = new GLabel(economicsSet, 223, 44, 130, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Municipal Budget");
  label2.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label2.setOpaque(false);
  label3 = new GLabel(economicsSet, 47, 137, 130, 27);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Economic Recession Rate");
  label3.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label3.setOpaque(false);
  label4 = new GLabel(economicsSet, 223, 136, 130, 28);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Population Growth Rate");
  label4.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label4.setOpaque(false);
  label5 = new GLabel(economicsSet, 47, 240, 130, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Commute Tolerance");
  label5.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label5.setOpaque(false);
  label6 = new GLabel(economicsSet, 223, 239, 130, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Population Density");
  label6.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label6.setOpaque(false);
  environmentSet.loop();
  economicsSet.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton genMap; 
GButton openEcon; 
GButton openEnv; 
GButton presetJ; 
GButton presetM; 
GButton presetO; 
GButton resetMap; 
GWindow environmentSet;
GCheckbox oceanCheck; 
GCheckbox mountainCheck; 
GCustomSlider setOcean; 
GCustomSlider setMountain; 
GCustomSlider setRain; 
GLabel enviro1; 
GLabel enviro2; 
GLabel enviro3; 
GButton closeEnviro; 
GWindow economicsSet;
GCustomSlider setGDP; 
GCustomSlider setMuni; 
GCustomSlider setComm; 
GCustomSlider setPopG; 
GCustomSlider setPopDen; 
GCustomSlider setEconR; 
GButton closeEconomics; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
