/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void openE(GButton source, GEvent event) { //_CODE_:openEnvironemnt:411614:
  println("openEnvironemnt - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:openEnvironemnt:411614:

public void openEcon(GButton source, GEvent event) { //_CODE_:openEconomics:233632:
  println("openEconomics - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:openEconomics:233632:

public void genMap(GButton source, GEvent event) { //_CODE_:mapGeneration:297302:
  println("mapGeneration - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:mapGeneration:297302:

public void set1(GButton source, GEvent event) { //_CODE_:preset1:824341:
  println("preset1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:preset1:824341:

public void set2(GButton source, GEvent event) { //_CODE_:preset2:809455:
  println("preset2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:preset2:809455:

public void set3(GButton source, GEvent event) { //_CODE_:preset3:460313:
  println("preset3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:preset3:460313:

synchronized public void envSet(PApplet appc, GWinData data) { //_CODE_:EnvironmentSettings:399990:
  appc.background(230);
} //_CODE_:EnvironmentSettings:399990:

public void sliderOcean(GCustomSlider source, GEvent event) { //_CODE_:oceanIntensity:257706:
  println("oceanIntensity - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:oceanIntensity:257706:

public void sliderMountain(GCustomSlider source, GEvent event) { //_CODE_:mountainIntensity:581695:
  println("mountainIntensity - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:mountainIntensity:581695:

public void sliderClimate(GCustomSlider source, GEvent event) { //_CODE_:climateFrequency:722911:
  println("climateFrequency - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:climateFrequency:722911:

public void toggleOcean(GCheckbox source, GEvent event) { //_CODE_:allowOcean:825702:
  println("allowOcean - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:allowOcean:825702:

public void toggleMountain(GCheckbox source, GEvent event) { //_CODE_:allowMountain:281316:
  println("allowMountain - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:allowMountain:281316:

public void closeE(GButton source, GEvent event) { //_CODE_:closeEnvGUI:834480:
  println("closeEnvGUI - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:closeEnvGUI:834480:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:EconomicSettings:251741:
  appc.background(230);
} //_CODE_:EconomicSettings:251741:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:gdp:462858:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:gdp:462858:

public void custom_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:municipialBudget:410812:
  println("custom_slider2 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:municipialBudget:410812:

public void custom_slider3_change1(GCustomSlider source, GEvent event) { //_CODE_:recession:492170:
  println("custom_slider3 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:recession:492170:

public void custom_slider4_change1(GCustomSlider source, GEvent event) { //_CODE_:populationGrowth:746917:
  println("custom_slider4 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:populationGrowth:746917:

public void custom_slider5_change1(GCustomSlider source, GEvent event) { //_CODE_:commuteTolerance:431981:
  println("custom_slider5 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:commuteTolerance:431981:

public void toggleDensity(GCustomSlider source, GEvent event) { //_CODE_:populationDensity:298534:
  println("custom_slider6 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:populationDensity:298534:

public void closeEcon(GButton source, GEvent event) { //_CODE_:clsoeEconGUI:881997:
  println("clsoeEconGUI - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:clsoeEconGUI:881997:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  openEnvironemnt = new GButton(this, 6, 333, 115, 45);
  openEnvironemnt.setText("Environment Settings");
  openEnvironemnt.addEventHandler(this, "openE");
  openEconomics = new GButton(this, 6, 418, 115, 45);
  openEconomics.setText("Economics    Settings");
  openEconomics.addEventHandler(this, "openEcon");
  mapGeneration = new GButton(this, 541, 11, 116, 55);
  mapGeneration.setText("Generate Map");
  mapGeneration.setLocalColorScheme(GCScheme.RED_SCHEME);
  mapGeneration.addEventHandler(this, "genMap");
  preset1 = new GButton(this, 1099, 341, 80, 30);
  preset1.setText("Preset 1");
  preset1.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  preset1.addEventHandler(this, "set1");
  preset2 = new GButton(this, 1099, 385, 80, 30);
  preset2.setText("Preset 2");
  preset2.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  preset2.addEventHandler(this, "set2");
  preset3 = new GButton(this, 1098, 430, 80, 30);
  preset3.setText("Preset 3");
  preset3.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  preset3.addEventHandler(this, "set3");
  EnvironmentSettings = GWindow.getWindow(this, "Environment", 0, 0, 350, 300, JAVA2D);
  EnvironmentSettings.noLoop();
  EnvironmentSettings.setActionOnClose(G4P.KEEP_OPEN);
  EnvironmentSettings.addDrawHandler(this, "envSet");
  oceanIntensity = new GCustomSlider(EnvironmentSettings, 49, 81, 100, 67, "grey_blue");
  oceanIntensity.setShowValue(true);
  oceanIntensity.setShowLimits(true);
  oceanIntensity.setLimits(0.5, 0.0, 1.0);
  oceanIntensity.setNbrTicks(5);
  oceanIntensity.setShowTicks(true);
  oceanIntensity.setNumberFormat(G4P.DECIMAL, 2);
  oceanIntensity.setOpaque(false);
  oceanIntensity.addEventHandler(this, "sliderOcean");
  mountainIntensity = new GCustomSlider(EnvironmentSettings, 209, 81, 100, 67, "grey_blue");
  mountainIntensity.setShowValue(true);
  mountainIntensity.setShowLimits(true);
  mountainIntensity.setLimits(5.0, 0.0, 10.0);
  mountainIntensity.setNbrTicks(5);
  mountainIntensity.setShowTicks(true);
  mountainIntensity.setNumberFormat(G4P.DECIMAL, 2);
  mountainIntensity.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  mountainIntensity.setOpaque(false);
  mountainIntensity.addEventHandler(this, "sliderMountain");
  climateFrequency = new GCustomSlider(EnvironmentSettings, 131, 198, 100, 61, "grey_blue");
  climateFrequency.setShowValue(true);
  climateFrequency.setShowLimits(true);
  climateFrequency.setLimits(0.1, 0.0, 1.0);
  climateFrequency.setNbrTicks(5);
  climateFrequency.setShowTicks(true);
  climateFrequency.setNumberFormat(G4P.DECIMAL, 2);
  climateFrequency.setOpaque(false);
  climateFrequency.addEventHandler(this, "sliderClimate");
  allowOcean = new GCheckbox(EnvironmentSettings, 38, 30, 120, 20);
  allowOcean.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  allowOcean.setText("Allow Ocean");
  allowOcean.setOpaque(false);
  allowOcean.addEventHandler(this, "toggleOcean");
  allowOcean.setSelected(true);
  allowMountain = new GCheckbox(EnvironmentSettings, 204, 32, 120, 20);
  allowMountain.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  allowMountain.setText("Allow Mountain");
  allowMountain.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  allowMountain.setOpaque(false);
  allowMountain.addEventHandler(this, "toggleMountain");
  allowMountain.setSelected(true);
  closeEnvGUI = new GButton(EnvironmentSettings, 261, 258, 80, 30);
  closeEnvGUI.setText("Close");
  closeEnvGUI.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  closeEnvGUI.addEventHandler(this, "closeE");
  label7 = new GLabel(EnvironmentSettings, 49, 61, 100, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Ocean Intensity");
  label7.setOpaque(false);
  label8 = new GLabel(EnvironmentSettings, 209, 53, 101, 27);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("Mountain Intensity");
  label8.setOpaque(false);
  label9 = new GLabel(EnvironmentSettings, 130, 176, 101, 20);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("Rain Intensity");
  label9.setOpaque(false);
  EconomicSettings = GWindow.getWindow(this, "Economics", 0, 0, 350, 300, JAVA2D);
  EconomicSettings.noLoop();
  EconomicSettings.setActionOnClose(G4P.KEEP_OPEN);
  EconomicSettings.addDrawHandler(this, "win_draw1");
  gdp = new GCustomSlider(EconomicSettings, 50, 39, 100, 51, "grey_blue");
  gdp.setLimits(0.5, 0.0, 1.0);
  gdp.setNumberFormat(G4P.DECIMAL, 2);
  gdp.setOpaque(false);
  gdp.addEventHandler(this, "custom_slider1_change1");
  municipialBudget = new GCustomSlider(EconomicSettings, 198, 38, 100, 52, "grey_blue");
  municipialBudget.setLimits(0.5, 0.0, 1.0);
  municipialBudget.setNumberFormat(G4P.DECIMAL, 2);
  municipialBudget.setOpaque(false);
  municipialBudget.addEventHandler(this, "custom_slider2_change1");
  recession = new GCustomSlider(EconomicSettings, 51, 121, 100, 49, "grey_blue");
  recession.setLimits(0.5, 0.0, 1.0);
  recession.setNumberFormat(G4P.DECIMAL, 2);
  recession.setOpaque(false);
  recession.addEventHandler(this, "custom_slider3_change1");
  populationGrowth = new GCustomSlider(EconomicSettings, 199, 120, 100, 49, "grey_blue");
  populationGrowth.setLimits(0.5, 0.0, 1.0);
  populationGrowth.setNumberFormat(G4P.DECIMAL, 2);
  populationGrowth.setOpaque(false);
  populationGrowth.addEventHandler(this, "custom_slider4_change1");
  commuteTolerance = new GCustomSlider(EconomicSettings, 50, 201, 100, 48, "grey_blue");
  commuteTolerance.setLimits(0.5, 0.0, 1.0);
  commuteTolerance.setNumberFormat(G4P.DECIMAL, 2);
  commuteTolerance.setOpaque(false);
  commuteTolerance.addEventHandler(this, "custom_slider5_change1");
  populationDensity = new GCustomSlider(EconomicSettings, 199, 200, 100, 49, "grey_blue");
  populationDensity.setLimits(0.5, 0.0, 1.0);
  populationDensity.setNumberFormat(G4P.DECIMAL, 2);
  populationDensity.setOpaque(false);
  populationDensity.addEventHandler(this, "toggleDensity");
  clsoeEconGUI = new GButton(EconomicSettings, 259, 258, 80, 30);
  clsoeEconGUI.setText("Close");
  clsoeEconGUI.addEventHandler(this, "closeEcon");
  label1 = new GLabel(EconomicSettings, 50, 172, 100, 28);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Commute Tolerance");
  label1.setOpaque(false);
  label2 = new GLabel(EconomicSettings, 197, 90, 99, 30);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Population Growth Rate");
  label2.setOpaque(false);
  label3 = new GLabel(EconomicSettings, 199, 170, 102, 29);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Populaiton Density");
  label3.setOpaque(false);
  label4 = new GLabel(EconomicSettings, 51, 91, 100, 28);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Economic Recession Rate");
  label4.setOpaque(false);
  label5 = new GLabel(EconomicSettings, 50, 19, 99, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("GDP Per Capita");
  label5.setOpaque(false);
  label6 = new GLabel(EconomicSettings, 198, 18, 101, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Municipal Budget");
  label6.setOpaque(false);
  EnvironmentSettings.loop();
  EconomicSettings.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton openEnvironemnt; 
GButton openEconomics; 
GButton mapGeneration; 
GButton preset1; 
GButton preset2; 
GButton preset3;
GWindow EnvironmentSettings;
GCustomSlider oceanIntensity; 
GCustomSlider mountainIntensity; 
GCustomSlider climateFrequency; 
GCheckbox allowOcean; 
GCheckbox allowMountain; 
GButton closeEnvGUI; 
GLabel label7; 
GLabel label8; 
GLabel label9; 
GWindow EconomicSettings;
GCustomSlider gdp; 
GCustomSlider municipialBudget; 
GCustomSlider recession; 
GCustomSlider populationGrowth; 
GCustomSlider commuteTolerance; 
GCustomSlider populationDensity; 
GButton clsoeEconGUI; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
